# Generated by Django 4.1 on 2022-08-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NcardInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("primary_organisation", models.CharField(max_length=255)),
                ("other_organisation", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=255)),
                ("Phone", models.CharField(max_length=255)),
                ("NCARD_collaborator", models.CharField(max_length=255)),
                ("Project", models.CharField(max_length=255)),
                ("Twitter_handle", models.CharField(max_length=255)),
            ],
        ),
    ]
