# Generated by Django 4.1 on 2022-08-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01test", "0003_country_grant_person_publication_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="noYear",
            field=models.DecimalField(decimal_places=1, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="award", name="notes", field=models.TextField(blank=True),
        ),
    ]
