# Generated by Django 4.1 on 2022-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01test", "0004_award_noyear_award_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="award", name="link", field=models.URLField(blank=True),
        ),
    ]
