# Generated by Django 4.1 on 2022-08-14 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=16)),
                ('given_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('surname', models.CharField(blank=True, max_length=64)),
                ('surname_first', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['surname', 'given_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=128)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_record', to='ncard_app.person')),
            ],
            options={
                'ordering': ['person'],
            },
        ),
    ]
