# Generated by Django 4.1 on 2022-08-22 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0002_organisation_contactrecord_personaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecord',
            name='phone_home',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone (home)'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone (mobile)'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='phone_office',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone (office)'),
        ),
    ]
