# Generated by Django 4.1 on 2022-08-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0006_grant_alter_country_options_grantinvestigator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='award',
            name='noYear',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
