# Generated by Django 4.1 on 2022-08-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0007_award_link_award_noyear_award_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='noYear',
        ),
        migrations.AddField(
            model_name='award',
            name='no_year',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=10),
        ),
    ]
