# Generated by Django 4.1 on 2022-09-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ncard_app', '0008_remove_award_noyear_award_no_year'), ('ncard_app', '0009_alter_award_no_year'), ('ncard_app', '0010_alter_award_no_year'), ('ncard_app', '0011_alter_award_no_year'), ('ncard_app', '0012_alter_award_no_year')]

    dependencies = [
        ('ncard_app', '0007_award_link_award_noyear_award_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='noYear',
        ),
        migrations.AddField(
            model_name='award',
            name='no_year',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=10, null=True),
        ),
    ]
