# Generated by Django 4.1 on 2022-08-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0011_alter_award_no_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='no_year',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=10, null=True),
        ),
    ]
