# Generated by Django 4.1 on 2022-09-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0013_rename_type_award_award_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.IntegerField(choices=[(1, 'Home'), (2, 'Work')])),
                ('line1', models.CharField(max_length=64, verbose_name='line 1')),
                ('line2', models.CharField(blank=True, max_length=64, verbose_name='line 2')),
                ('line3', models.CharField(blank=True, max_length=64, verbose_name='line 3')),
                ('suburb', models.CharField(blank=True, max_length=32)),
                ('state', models.CharField(blank=True, max_length=3, verbose_name='state (abbrev.)')),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.ForeignKey(default='AU', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ncard_app.country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ncard_app.person')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.AddConstraint(
            model_name='personaddress',
            constraint=models.UniqueConstraint(fields=('person', 'address_type'), name='address_unique_person_address_type'),
        ),
    ]
