# Generated by Django 4.1 on 2022-09-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0013_remove_personaddress_address_unique_person_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaddress',
            old_name='address_type',
            new_name='type',
        ),
        migrations.RemoveIndex(
            model_name='personaddress',
            name='ncard_app_p_person__eee929_idx',
        ),
        migrations.RenameField(
            model_name='personaddress',
            old_name='type',
            new_name='address_type',
        ),
    ]
