# Generated by Django 4.1 on 2022-10-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0014_personaddress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRecord',
        ),
    ]
