# Generated by Django 4.1 on 2022-10-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0016_person_clinician_person_cre_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='recipients',
            field=models.ManyToManyField(related_name='awards', to='ncard_app.person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lead_contacts',
            field=models.ManyToManyField(blank=True, related_name='events', to='ncard_app.person'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='investigators',
            field=models.ManyToManyField(related_name='grants', through='ncard_app.GrantInvestigator', to='ncard_app.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='employers',
            field=models.ManyToManyField(blank=True, related_name='employees', to='ncard_app.organisation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organisation_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_other_org', to='ncard_app.organisation', verbose_name='organisation (other)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organisation_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_primary_org', to='ncard_app.organisation', verbose_name='organisation (primary)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contributors',
            field=models.ManyToManyField(related_name='publications', to='ncard_app.person'),
        ),
    ]
