# Generated by Django 4.1 on 2022-10-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0016_person_clinician_person_cre_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.IntegerField(choices=[(1, 'Honours'), (2, 'Phd')], verbose_name='student type')),
                ('title_topic', models.TextField(blank=True, verbose_name='title topic')),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year start')),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year end')),
                ('scholarship', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award', to='ncard_app.award')),
                ('student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='ncard_app.person')),
                ('supervisor', models.ManyToManyField(blank=True, to='ncard_app.person')),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
    ]
