# Generated by Django 4.1 on 2022-10-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0017_alter_award_recipients_alter_event_lead_contacts_and_more'),
        ('ncard_app', '0017_students'),
    ]

    operations = [
    ]
