# Generated by Django 4.1 on 2022-10-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0017_students'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='person',
            new_name='Person_surname_2b0d3e_idx',
            old_name='ncard_app_p_surname_4edca3_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='Person_given_n_55be79_idx',
            old_name='ncard_app_p_given_n_7cc51c_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='Project_name_f73564_idx',
            old_name='ncard_app_p_name_cc5b7d_idx',
        ),
        migrations.AlterModelTable(
            name='award',
            table='Award',
        ),
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
        migrations.AlterModelTable(
            name='grant',
            table='Grant',
        ),
        migrations.AlterModelTable(
            name='grantinvestigator',
            table='GrantInvestigator',
        ),
        migrations.AlterModelTable(
            name='organisation',
            table='Organisation',
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
        migrations.AlterModelTable(
            name='personaddress',
            table='PersonAddress',
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.AlterModelTable(
            name='publication',
            table='Publication',
        ),
        migrations.AlterModelTable(
            name='students',
            table='Student',
        ),
    ]
