# Generated by Django 4.1 on 2022-10-09 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0018_rename_ncard_app_p_surname_4edca3_idx_person_surname_2b0d3e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone'),
        ),
    ]
