# Generated by Django 4.1 on 2022-10-12 02:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0018_merge_20221008_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['student_name'], 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='award',
            name='detail',
            field=models.TextField(blank=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='award',
            name='no_year',
            field=models.DecimalField(blank=True, decimal_places=0, default=1.0, max_digits=10, null=True, verbose_name='Concurrent Years'),
        ),
        migrations.AlterField(
            model_name='award',
            name='status',
            field=models.IntegerField(choices=[(1, 'Awardee'), (2, 'Nominee'), (3, 'Finalist')], default=1, verbose_name='award Status'),
        ),
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='year Established'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='person',
            name='clinician',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='cre_role',
            field=models.CharField(blank=True, max_length=15, verbose_name='CRE Role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Primary Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Secondary Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(max_length=64, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn (URL)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='loop_profile',
            field=models.URLField(blank=True, verbose_name='Loop Profile'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organisation_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_other_org', to='ncard_app.organisation', verbose_name='Organisation (Other)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organisation_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_primary_org', to='ncard_app.organisation', verbose_name='Organisation (Primary)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_home',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone (Home)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone (Mobile)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_office',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone (Office)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_url',
            field=models.URLField(blank=True, verbose_name='Profile URL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='research_focus',
            field=models.CharField(blank=True, max_length=255, verbose_name='Research Focus'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^$|^@[A-Za-z0-9_]+$', 'Twitter handle must begin with an @ and only contain letters, digits and underscores.')], verbose_name='Twitter Handle (please include "@")'),
        ),
    ]
