# Generated by Django 4.1 on 2022-10-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0019_alter_organisation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
    ]
