# Generated by Django 4.1 on 2022-10-09 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0020_alter_organisation_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^$|^@[A-Za-z0-9_]+$', 'Twitter handle must begin with an @ and only contain letters, digits and underscores.')], verbose_name='Twitter handle'),
        ),
    ]
