# Generated by Django 4.1 on 2022-10-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0020_alter_award_name_alter_award_no_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['student_name']},
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='Person_surname_2b0d3e_idx',
            old_name='ncard_app_p_surname_4edca3_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='Person_given_n_55be79_idx',
            old_name='ncard_app_p_given_n_7cc51c_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='Project_name_f73564_idx',
            old_name='ncard_app_p_name_cc5b7d_idx',
        ),
        migrations.AddField(
            model_name='person',
            name='address_type',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'Work')], default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(default='AU', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ncard_app.country'),
        ),
        migrations.AddField(
            model_name='person',
            name='line1',
            field=models.CharField(default='', max_length=64, verbose_name='line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='line2',
            field=models.CharField(blank=True, max_length=64, verbose_name='line 2'),
        ),
        migrations.AddField(
            model_name='person',
            name='line3',
            field=models.CharField(blank=True, max_length=64, verbose_name='line 3'),
        ),
        migrations.AddField(
            model_name='person',
            name='postcode',
            field=models.CharField(default='—', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(blank=True, max_length=3, verbose_name='state (abbrev.)'),
        ),
        migrations.AddField(
            model_name='person',
            name='suburb',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Awwrd Name'),
        ),
        migrations.AlterModelTable(
            name='award',
            table='Award',
        ),
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
        migrations.AlterModelTable(
            name='grant',
            table='Grant',
        ),
        migrations.AlterModelTable(
            name='grantinvestigator',
            table='GrantInvestigator',
        ),
        migrations.AlterModelTable(
            name='organisation',
            table='Organisation',
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.AlterModelTable(
            name='publication',
            table='Publication',
        ),
        migrations.AlterModelTable(
            name='students',
            table='Student',
        ),
    ]
