# Generated by Django 4.1 on 2022-10-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0020_alter_award_name_alter_award_no_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Award Name'),
        ),
    ]
