# Generated by Django 4.1 on 2022-10-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0021_alter_award_name'),
        ('ncard_app', '0021_alter_students_options_and_more'),
    ]

    operations = [
    ]
