# Generated by Django 4.1 on 2022-10-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0024_alter_event_detail_alter_event_number_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Home'), (2, 'Work')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='line1',
            field=models.CharField(blank=True, max_length=64, verbose_name='line 1'),
        ),
    ]
