# Generated by Django 4.1 on 2022-10-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0025_alter_person_address_type_alter_person_line1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Home'), (2, 'Work')]),
        ),
    ]
