# Generated by Django 4.1 on 2022-10-14 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0026_alter_person_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='home_country',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='line1',
            new_name='home_line1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='line2',
            new_name='home_line2',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='line3',
            new_name='home_line3',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='state',
            new_name='home_state',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='suburb',
            new_name='home_suburb',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postcode',
        ),
        migrations.AddField(
            model_name='person',
            name='home_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='work_country',
            field=models.ForeignKey(default='AU', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ncard_app.country'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_line1',
            field=models.CharField(blank=True, max_length=64, verbose_name='line 1'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_line2',
            field=models.CharField(blank=True, max_length=64, verbose_name='line 2'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_line3',
            field=models.CharField(blank=True, max_length=64, verbose_name='line 3'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='work_state',
            field=models.CharField(blank=True, max_length=3, verbose_name='state (abbrev.)'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_suburb',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
