# Generated by Django 4.1 on 2022-10-14 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0027_rename_country_person_home_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_country',
            field=models.ForeignKey(default='AU', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ncard_app.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_line1',
            field=models.CharField(blank=True, max_length=64, verbose_name='Line 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_line2',
            field=models.CharField(blank=True, max_length=64, verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_line3',
            field=models.CharField(blank=True, max_length=64, verbose_name='Line 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_state',
            field=models.CharField(blank=True, max_length=3, verbose_name='State (abbrev.)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_suburb',
            field=models.CharField(blank=True, max_length=32, verbose_name='Suburb'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_country',
            field=models.ForeignKey(default='AU', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ncard_app.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_line1',
            field=models.CharField(blank=True, max_length=64, verbose_name='Line 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_line2',
            field=models.CharField(blank=True, max_length=64, verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_line3',
            field=models.CharField(blank=True, max_length=64, verbose_name='Line 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_state',
            field=models.CharField(blank=True, max_length=3, verbose_name='State (abbrev.)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_suburb',
            field=models.CharField(blank=True, max_length=32, verbose_name='Suburb'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(verbose_name='title'),
        ),
    ]
