# Generated by Django 4.1 on 2022-10-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0030_alter_organisation_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_attendees',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of Attendees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.TextField(blank=True, null=True, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
