# Generated by Django 4.1 on 2022-10-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0031_alter_event_detail_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lead_contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='ncard_app.person'),
        ),
    ]
