# Generated by Django 4.1 on 2022-10-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0032_alter_event_date_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TextField(blank=True, null=True, verbose_name='date'),
        ),
    ]
