# Generated by Django 4.1 on 2022-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0034_alter_event_date_alter_event_number_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.TextField(max_length=255, verbose_name='publication type'),
        ),
    ]
