# Generated by Django 4.1 on 2022-10-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0037_alter_event_number_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_attendees',
            field=models.TextField(blank=True, null=True, verbose_name='number of Attendees'),
        ),
    ]
