# Generated by Django 4.1 on 2022-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0039_alter_award_award_type_alter_person_employers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='page_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='end page'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='start page'),
        ),
    ]
