# Generated by Django 4.1 on 2022-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0040_alter_publication_page_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Prize'), (2, 'Scholarship'), (3, 'Award'), (4, 'Grant')], null=True, verbose_name='type'),
        ),
    ]
