# Generated by Django 4.1 on 2022-10-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0041_alter_award_award_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year Established'),
        ),
    ]
