# Generated by Django 4.1 on 2022-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0043_alter_award_link_alter_award_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='source_ID',
            field=models.CharField(blank=True, max_length=255, verbose_name='source ID'),
        ),
    ]
